# Generated by Django 4.1.4 on 2022-12-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=30
            ),
        ),
    ]
